blank_issues_enabled: false
contact_links:
    - name: ğŸ“š ë¬¸ì„œ
      url: https://github.com/Hyundai-Autoever-Smart-Factory-2nd/battery3080-backend/wiki
      about: í”„ë¡œì íŠ¸ ë¬¸ì„œì™€ ê°€ì´ë“œë¥¼ í™•ì¸í•´ë³´ì„¸ìš”.
    - name: ğŸ’¬ ë””ìŠ¤ì»¤ì…˜
      url: https://github.com/Hyundai-Autoever-Smart-Factory-2nd/battery3080-backend/discussions
      about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ ë””ìŠ¤ì»¤ì…˜ì„ ì´ìš©í•´ì£¼ì„¸ìš”.
